<a href="https://colab.research.google.com/github/Bindhya-K/Practice-session/blob/main/NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [3]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
#Code here
np.where(np.arange(10)==4,1,0)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [5]:
#Code here
inp1 = int(input('enter first number'))
inp2 = int(input('enter second number'))
x = np.random.random((inp1,inp2))
print(x)
print('average of the array:',np.mean(x))


enter first number2
enter second number3
[[0.31873067 0.40875668 0.13551776]
 [0.26329728 0.17668634 0.83627079]]
average of the array: 0.35654325299375894


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [16]:
#Code here
def twodimarray(a,b):
  x=np.ones((a,b),dtype=int)
  x[1:a-1,1:b-1]=0
  return x

twodimarray(5,5)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [19]:
#Code here
x=np.linspace(0.1,1,10,endpoint=False)
print(x)

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [25]:
#Code here
No



###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [29]:
np.linspace(0,4,25).reshape(5,5)

array([[0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667],
       [0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ],
       [1.66666667, 1.83333333, 2.        , 2.16666667, 2.33333333],
       [2.5       , 2.66666667, 2.83333333, 3.        , 3.16666667],
       [3.33333333, 3.5       , 3.66666667, 3.83333333, 4.        ]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [33]:
#code here
x = np.random.random((10,2))
x = np.round(x*100)
print('Co-ordinates Array',x)
point = np.array([2,3])
dist = x-point
print('Distance Array=',dist)

Co-ordinates Array [[17. 88.]
 [ 5. 81.]
 [11. 54.]
 [25. 19.]
 [72. 64.]
 [48. 56.]
 [72.  0.]
 [41. 22.]
 [59. 20.]
 [30. 73.]]
Distance Array= [[15. 85.]
 [ 3. 78.]
 [ 9. 51.]
 [23. 16.]
 [70. 61.]
 [46. 53.]
 [70. -3.]
 [39. 19.]
 [57. 17.]
 [28. 70.]]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [39]:
#Code here
x = np.ones((6,7,8))
np.unravel_index(100-1,x.shape)

(1, 5, 3)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [44]:
#Code here
inp = '1 2 3 4 -8 -10'
x = []
for i in inp.split():
  x.append(i)
  y = np.array(x,dtype=float)
print(np.flip(y))


[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [46]:
#Code here
x = np.array([])
count=0
for i in x:
  count+=1
print(count)

0


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [50]:
#Code here
def softmaxfn(a):
  out=np.array([])
  if np.ndim(a)==1:
    dr = np.sum(np.exp(a))
    out = np.exp(a)/dr
  else:
    raise Exception('Only 1D are allowed')
  return out
softmaxfn(np.array([33.17344305,45.61961654,82.05405781,80.9647098,68.82830233,91.52064278]))

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [58]:
#Coder here
def vst(*args):

  x = np.vstack((args))
  return x
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b = np.array([[1,1,1,1,1],[1,1,1,1,1]])
c = np.array([[0.10117373,0.1677244,0.73764059,0.83166097,0.48985695],[0.44581567,0.13502419,0.55692335,0.16479622,0.61193593]] )
vst(a,b,c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here
def date_array(start,end):
  x = np.

###`Q-14:` Subtract the mean of each row from a matrix.

In [67]:
#code here
x = np.arange(9).reshape(3,3)
print('Matrix',x)
mean_x = np.mean(x,axis=1)
print(mean_x)
print('subtracted matrix',x-mean_x)

Matrix [[0 1 2]
 [3 4 5]
 [6 7 8]]
[1. 4. 7.]
subtracted matrix [[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [63]:
#Code here
a=np.arange(12).reshape(3,4)
print(a)
a[:,[0,1]]=a[:,[1,0]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

In [52]:
x=np.array([2,4,2,4,6,3,1,4,5,7,9,11])
x[x%2!=0]=-1
x


array([ 2,  4,  2,  4,  6, -1, -1,  4, -1, -1, -1, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [32]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
x=[]
for i in range(len(a)):
  if a[i]<b[i]:
    x.append(b[i])
  else:
    x.append(a[i])
x


[6, 3, 1, 7, 8]

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [15]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[9987, 7263, 4754,  297, 7769],
       [1813, 4963,  636, 8794, 4718],
       [4575, 4475,  178, 9218, 5603],
       [7554, 1437, 7457, 4413, 8106],
       [3977, 4205, 8331, 8162, 7642],
       [1114, 1872, 7820, 5611, 8176],
       [6158, 3392, 6911,  480,  969],
       [8868, 1358, 2763, 3410, 6849]])

In [18]:
#Code here
arr1[:,::2]

array([[9987, 4754, 7769],
       [1813,  636, 4718],
       [4575,  178, 5603],
       [7554, 7457, 8106],
       [3977, 8331, 7642],
       [1114, 7820, 8176],
       [6158, 6911,  969],
       [8868, 2763, 6849]])

In [19]:
def normalize(arr1):
  return (arr1-np.min(arr1))/(np.max(arr1)-np.min(arr1))
normalize(arr1)

array([[1.        , 0.72229585, 0.46651035, 0.01213172, 0.77388113],
       [0.16668366, 0.48781731, 0.04669181, 0.878377  , 0.46284025],
       [0.4482618 , 0.43806708, 0.        , 0.92160261, 0.55306351],
       [0.75196248, 0.12835151, 0.74207361, 0.43174636, 0.80823733],
       [0.38729738, 0.41054134, 0.83117545, 0.81394638, 0.76093384],
       [0.09542257, 0.17269854, 0.77908044, 0.55387909, 0.81537364],
       [0.6096442 , 0.32765827, 0.68641044, 0.03078805, 0.08064023],
       [0.88592109, 0.12029769, 0.26353349, 0.32949332, 0.68008971]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [11]:
#Code here
def largest(arr,n):
  if n<=len(arr):
    arr = np.flip(np.sort(arr))
    print('the {}the largest item of the array is {}'.format(n,arr[n-1]))
  else:
    raise Exception("the value of n shouldn't be larger than the array length")
largest([12,34,40,7,1,0],3)


the 3the largest item of the array is 12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [9]:
#code here
a = np.array([1,2,3])
b=np.repeat(a,3)
c=np.tile(a,3)
print(b)
print(c)
x=np.hstack((b,c))
print(x)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
